#!/bin/bash
apps=$(grep -hE "^(Name|Exec)=" /usr/share/applications/*.desktop ~/.local/share/applications/*.desktop 2>/dev/null|awk -F= '/^Name=/{n=$2}/^Exec=/{e=$2;sub(/%.*/,"",e);print n"\t"e}'|sort -u)
selected=$(fzf --delimiter=$'\t' --with-nth=1 --layout=reverse --border --prompt="Launch > "<<<"$apps")||exec bash
setsid bash -c "$(echo "$selected"|cut -f2)" &>/dev/null &
sleep 0.1
kill $PPID
